//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1_compile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab1_compile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Справка - руководство по использованию&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///        }
        ///
        ///        h1, h2, h3 {
        ///            margin-top: 25px;
        ///        }
        ///
        ///        ul, ol {
        ///            line-height: 1.6;
        ///        }
        ///
        ///        a {
        ///            color: #0066cc;
        ///            text-decoration: none;
        ///        }
        ///
        ///            a:hover {
        ///                text-de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Справка - руководство по использованию&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///        }
        ///
        ///        h1, h2, h3 {
        ///            margin-top: 25px;
        ///        }
        ///
        ///        ul, ol {
        ///            line-height: 1.6;
        ///        }
        ///
        ///        a {
        ///            color: #0066cc;
        ///            text-decoration: none;
        ///        }
        ///
        ///            a:hover {
        ///                text-de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;РњРµС‚РѕРґ Р°РЅР°Р»РёР·Р°&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.6;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 24px;
        ///        }
        ///
        ///        img {
        ///            width: 30%;
        ///            display: block;
        ///            margin: 20px auto;
        ///            border: 1px solid #ccc;
        ///            border-radius: 6px;
        ///        }
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string analysis {
            get {
                return ResourceManager.GetString("analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Метод анализа&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.6;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 24px;
        ///        }
        ///
        ///        img {
        ///            width: 30%;
        ///            display: block;
        ///            margin: 20px auto;
        ///            border: 1px solid #ccc;
        ///            border-radius: 6px;
        ///        }
        ///
        ///        figcaption [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string analysis1 {
            get {
                return ResourceManager.GetString("analysis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Список литературы&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.7;
        ///        }
        ///
        ///        h1 {
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        ol {
        ///            margin-left: 20px;
        ///        }
        ///
        ///        li {
        ///            margin-bottom: 10px;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Список литературы&lt;/h1&gt;
        ///    
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Шорников Ю.В.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bibliography {
            get {
                return ResourceManager.GetString("bibliography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_page {
            get {
                object obj = ResourceManager.GetObject("blank-page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Классификация грамматики&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.6;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 22px;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        code {
        ///            background-color: #f2f2f2;
        ///            padding: 2px 6px;
        ///            border-radius: 4px;
        ///            font-family: Consolas, mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string classification {
            get {
                return ResourceManager.GetString("classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_two_paper_sheets_interface_symbol {
            get {
                object obj = ResourceManager.GetObject("copy-two-paper-sheets-interface-symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Directory {
            get {
                object obj = ResourceManager.GetObject("Directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Диагностика и нейтрализация ошибок&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.7;
        ///        }
        ///
        ///        h1, h2 {
        ///            margin-top: 25px;
        ///        }
        ///
        ///        ol {
        ///            margin-left: 20px;
        ///        }
        ///
        ///        code {
        ///            background-color: #f2f2f2;
        ///            padding: 2px 6px;
        ///            border-radius: 4px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errors {
            get {
                return ResourceManager.GetString("errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder__1_ {
            get {
                object obj = ResourceManager.GetObject("folder (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Грамматика комплексных чисел&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.7;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 24px;
        ///            margin-bottom: 15px;
        ///        }
        ///
        ///        h2 {
        ///            margin-top: 30px;
        ///        }
        ///
        ///        pre {
        ///            background-color: #f8f8f8;
        ///            padding: 15px;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grammar {
            get {
                return ResourceManager.GetString("grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Исходный код программы&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.7;
        ///        }
        ///
        ///        h1, h2 {
        ///            margin-top: 25px;
        ///        }
        ///
        ///        pre {
        ///            background-color: #f5f5f5;
        ///            padding: 15px;
        ///            border-radius: 5px;
        ///            overflow-x: auto;
        ///            font-family: Consolas, monospace;
        ///            line [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_button {
            get {
                object obj = ResourceManager.GetObject("play-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scheme1 {
            get {
                object obj = ResourceManager.GetObject("Scheme1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scissors {
            get {
                object obj = ResourceManager.GetObject("scissors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;РџРѕСЃС‚Р°РЅРѕРІРєР° Р·Р°РґР°С‡Рё вЂ” РљРѕРјРїР»РµРєСЃРЅС‹Рµ С‡РёСЃР»Р°&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.6;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 24px;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        code {
        ///            background-color: #f2f2f2;
        ///            padding: 2px 6px;
        ///            border-radi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Постановка задачи — Комплексные числа&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.6;
        ///        }
        ///
        ///        h1 {
        ///            font-size: 24px;
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        code {
        ///            background-color: #f2f2f2;
        ///            padding: 2px 6px;
        ///            border-radius: 4px;
        ///            font-family: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string task1 {
            get {
                return ResourceManager.GetString("task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Тестовые примеры&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Segoe UI, sans-serif;
        ///            margin: 30px;
        ///            line-height: 1.7;
        ///        }
        ///
        ///        h1, h2 {
        ///            margin-top: 25px;
        ///        }
        ///
        ///        .example-container {
        ///            display: grid;
        ///            grid-template-columns: repeat(2, 1fr);
        ///            gap: 20px;
        ///            margin: 20px 0;
        ///        }
        ///
        ///        .example-item {
        ///            text- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_example {
            get {
                return ResourceManager.GetString("test_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test1 {
            get {
                object obj = ResourceManager.GetObject("Test1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test2 {
            get {
                object obj = ResourceManager.GetObject("Test2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test3 {
            get {
                object obj = ResourceManager.GetObject("Test3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test4 {
            get {
                object obj = ResourceManager.GetObject("Test4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree1 {
            get {
                object obj = ResourceManager.GetObject("tree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree2 {
            get {
                object obj = ResourceManager.GetObject("tree2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
